/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as LandingChangelogIndexRouteImport } from './routes/_landing/changelog/index'
import { Route as LandingBlogsIndexRouteImport } from './routes/_landing/blogs/index'
import { Route as LandingChangelogSlugRouteImport } from './routes/_landing/changelog/$slug'
import { Route as LandingBlogsSlugRouteImport } from './routes/_landing/blogs/$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const LandingChangelogIndexRoute = LandingChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogsIndexRoute = LandingBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingChangelogSlugRoute = LandingChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogsSlugRoute = LandingBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => LandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/privacy': typeof LandingPrivacyRoute
  '/terms': typeof LandingTermsRoute
  '/login': typeof PublicLoginRoute
  '/blogs/$slug': typeof LandingBlogsSlugRoute
  '/changelog/$slug': typeof LandingChangelogSlugRoute
  '/blogs/': typeof LandingBlogsIndexRoute
  '/changelog/': typeof LandingChangelogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/privacy': typeof LandingPrivacyRoute
  '/terms': typeof LandingTermsRoute
  '/login': typeof PublicLoginRoute
  '/blogs/$slug': typeof LandingBlogsSlugRoute
  '/changelog/$slug': typeof LandingChangelogSlugRoute
  '/blogs': typeof LandingBlogsIndexRoute
  '/changelog': typeof LandingChangelogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_landing/': typeof LandingIndexRoute
  '/_landing/blogs/$slug': typeof LandingBlogsSlugRoute
  '/_landing/changelog/$slug': typeof LandingChangelogSlugRoute
  '/_landing/blogs/': typeof LandingBlogsIndexRoute
  '/_landing/changelog/': typeof LandingChangelogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/blogs/$slug'
    | '/changelog/$slug'
    | '/blogs/'
    | '/changelog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/blogs/$slug'
    | '/changelog/$slug'
    | '/blogs'
    | '/changelog'
  id:
    | '__root__'
    | '/_authed'
    | '/_landing'
    | '/_public'
    | '/_authed/dashboard'
    | '/_landing/privacy'
    | '/_landing/terms'
    | '/_public/login'
    | '/_landing/'
    | '/_landing/blogs/$slug'
    | '/_landing/changelog/$slug'
    | '/_landing/blogs/'
    | '/_landing/changelog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_landing/changelog/': {
      id: '/_landing/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof LandingChangelogIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blogs/': {
      id: '/_landing/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof LandingBlogsIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/changelog/$slug': {
      id: '/_landing/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof LandingChangelogSlugRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blogs/$slug': {
      id: '/_landing/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof LandingBlogsSlugRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LandingRouteChildren {
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingBlogsSlugRoute: typeof LandingBlogsSlugRoute
  LandingChangelogSlugRoute: typeof LandingChangelogSlugRoute
  LandingBlogsIndexRoute: typeof LandingBlogsIndexRoute
  LandingChangelogIndexRoute: typeof LandingChangelogIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingBlogsSlugRoute: LandingBlogsSlugRoute,
  LandingChangelogSlugRoute: LandingChangelogSlugRoute,
  LandingBlogsIndexRoute: LandingBlogsIndexRoute,
  LandingChangelogIndexRoute: LandingChangelogIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
